services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  app:
    image: friendica
    restart: always
    volumes:
      - /portainer/Config/friendica:/var/www/html
    ports:
      - "8080:80"
    environment:
      - FRIENDICA_TZ=${FRIENDICA_TZ}
      - FRIENDICA_LANG=${FRIENDICA_LANG}
      - FRIENDICA_URL=${FRIENDICA_URL}
      - FRIENDICA_SITENAME=${FRIENDICA_SITENAME}
      - SMTP=${SMTP}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - FRIENDICA_ADMIN_MAIL=${MAILNAME}
    depends_on:
      - db

volumes:
  db:
  friendica:
