version: "3"

services:
   guacd:
         container_name: guacd
         image: guacamole/guacd
         restart: unless-stopped
         networks:
            guac-net:
               ipv4_address: ${IP_ADDRESS}
            
   guacweb:
      container_name: guac_web
      image: guacamole/guacamole
      restart: unless-stopped
      ports: ${PORT}
      environment:
       MYSQL_DATABASE: guacamole_db 
       MYSQL_HOSTNAME: ${SQL_HOST_IP}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
       MYSQL_USER: ${MYSQL_USER}
       GUAC_HOSTNAME: ${IP_ADDRESS}
	   
      depends_on:
     - guacamole_sql
     - guacd

      networks:
         guac-net:
         
   guacamole_sql:
      container_name: guac_sql
      image: mysql
      restart: unless-stopped
      environment:
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
	  - dbdata:/var/lib/mysql
	  
      networks:
         guac-net:
            ipv4_address: ${SQL_HOST_IP}
            
volumes:
   dbdata:
    
networks:
   guac-net:
      driver: bridge
      ipam:
         driver: default
         config:
   subnet: ${SUBNET}
   
