services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /portainer/Config/karakeep:/data
    ports:
      - "${PORTS}"
    environment:
      MEILI_ADDR: $MEILI_ADDR
      DATA_DIR: /data # DON'T CHANGE THIS
      
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data

volumes:
  meilisearch:
  data:
