services:
    romm:
        image: rommapp/romm:latest
        container_name: romm
        restart: unless-stopped
        environment:
            - DB_HOST=romm-db
            - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
            - DB_USER=${DB_USER} # Should match MARIADB_USER in mariadb
            - DB_PASSWD=${DB_PASSWD} # Should match MARIADB_PASSWORD in mariadb
            - ROMM_AUTH_SECRET_KEY=${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
            #- SCREENSCRAPER_USER= # These are the recommended metadata providers
            #- SCREENSCRAPER_PASSWORD= # https://docs.romm.app/latest/getting-started/metadata-providers/#screenscraper
            #- RETROACHIEVEMENTS_API_KEY= # https://docs.romm.app/latest/getting-started/metadata-providers/#retroachievements
            #- STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/getting-started/metadata-providers/#steamgriddb
            - HASHEOUS_API_ENABLED=true # https://docs.romm.app/latest/getting-started/metadata-providers/#hasheous
        volumes:
            - /portainer/Config/romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
            - /portainer/Config/romm/redis_data:/redis-data # Cached data for background tasks
            - /portainer/Downloads/ROMS:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
            - /portainer/Config/romm/assets:/romm/assets # Uploaded saves, states, etc.
            - /portainer/Config/romm/config:/romm/config # Path where config.yml is stored
          ports:
            - 86:8080    

    romm-db:
        image: mariadb:latest
        container_name: romm-db
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PWD}
            - MARIADB_DATABASE=romm
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWD}
        volumes:
            - /portainer/Config/romm/mysql:/var/lib/mysql

            
